name: registry
version: 0.6.2.0
synopsis: data structure for assembling components

description: This library provides a "Registry" which is a data structure containing
             a list of functions and values representing dependencies in a
             directed acyclic graph.
             A `make` function can then be used to create a value of a specific
             type out of the registry.

             You can start with the [README](https://github.com/etorreborre/registry/blob/master/README.md)
             for a full description of the library.

extra-source-files: README.md

category: Control

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry

language: GHC2021

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -optP-Wno-nonportable-include-path

default-extensions:
 - DefaultSignatures
 - FunctionalDependencies
 - GADTs
 - LambdaCase
 - MultiWayIf
 - NoImplicitPrelude
 - OverloadedStrings
 - PatternSynonyms
 - StrictData
 - TypeFamilies
 - TypeFamilyDependencies

dependencies:
  - base                  >= 4.14 && < 5
  - containers            >= 0.5  && < 0.7
  - exceptions            >= 0.8  && < 0.11
  - hashable              >= 1.2  && < 1.5
  - mtl                   >= 2.0  && < 3
  - mmorph                >= 1.0  && < 2
  - multimap              >= 1.0  && < 2
  - protolude             >= 0.2  && < 0.4
  - resourcet             >= 1.1  && < 2
  - semigroupoids         >= 5.0  && < 7
  - semigroups            >= 0.15 && < 0.30
  - template-haskell      >= 2.13 && < 3.0
  - text                  >= 1.1  && < 3
  - transformers-base     >= 0.4  && < 0.5
  - unliftio              >= 0.2  && < 1

library:
  source-dirs: src

  ghc-options:
    -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry
      - async            < 2.3
      - bytestring       < 0.12
      - directory        < 1.4
      - hedgehog         >= 1.0 && < 3.0
      - generic-lens     >= 1.0 && < 3.0
      - io-memoize       < 1.2
      - MonadRandom      < 1
      - multimap         < 2
      - semigroups       < 0.30
      - random           < 2.0
      - tasty            < 1.5
      - tasty-discover   < 6
      - tasty-hedgehog   >= 1.2 && < 2.0
      - tasty-th         < 0.2
      - text             < 3
      - universum        < 2

    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -fno-warn-incomplete-uni-patterns
      -optP-Wno-nonportable-include-path
