resolver: lts-19.6

packages:
- '.'

extra-deps:
- hedgehog-1.0.5
- tasty-hedgehog-1.0.1.0
- github: sdiehl/protolude
  commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b

flags: {}

extra-package-dbs: []
